### ISSUE TITLE
Supporting more attributes

### ISSUE THREAD

**Issue by krystianmagdziarz** [pnowosie/ifirma-api#8]
Are you considering supporting elements such as:

```
    invoice_dict = make_invoice(invoice)
    invoice_dict.update({
        "PodpisWystawcy": "Krystian MAGDZIARZ",
        "WidocznyNumerBdo": True,
        "NazwaSzablonu": None,
        "SposobZaplaty": payment,
        "Kontrahent": {
            "Nazwa": order_data['customer']['company'],
            "Identyfikator": None,
            "PrefiksUE": None,
            "NIP": order_data['customer']['vat_number'],
            "Ulica": order_data['customer']['address1'],
            "KodPocztowy": order_data['customer']['postcode'],
            "Kraj": "Polska",
            "Miejscowosc": order_data['customer']['city'],
            "Email": order_data['customer']['email'],
            "Telefon": order_data['customer']['phone'],
            "OsobaFizyczna": True if order_data['customer']['vat_number'] else False
        },
        "ProceduryJpk": {
            "SW": True
        }
    })

    create_invoice_response = custom_send_invoice(invoice_dict)
```
?

**Comment by pnowosie** [comment]
Hi Krystian,

👉  **TL;DR: I won't** 👈 

Thanks for the message and really insightful snippet!
I guess you might already know the answer from the time passed between your post and my reply. 

**No, I won't. I don't believe I could be able to catch up with a frequent changes of the accounting law.**
Sorry if I disappointed you ;)

Main goal behind this code is to support the very narrow needs of mine.
To be honest I haven't considered to accept PRs because of this.
I've sort of learnt to code in python during this journey as well.

**Comment by pnowosie** [comment]
I added language hint in the above markdown's snippet
<pre>```python</pre>
